# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c98e9b9c857dc00ca4df93502a8bf7baf150775616f261a03791a85aa033a1e49ea4edc240b52c9a36ceb014fef476f02bf922018f5f913b6334cc90a9d433b5

test:
  secret_key_base: 56c8abd12e84a49d02c4e0cf9bef965adcfc78dd1a6445e091bbf91121cd4a2cb47bee5a4111ccd9119c1cc2927e4afb55fd06e4c0ce091be188bd1efd505ffc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
